#Numpy Implimentation

In [1]:
import numpy as np

In [2]:
I = np.identity(3)

In [3]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
b = (9*I)+1

In [5]:
b

array([[10.,  1.,  1.],
       [ 1., 10.,  1.],
       [ 1.,  1., 10.]])

In [6]:
ans = np.dot(I,b)

In [7]:
ans

array([[10.,  1.,  1.],
       [ 1., 10.,  1.],
       [ 1.,  1., 10.]])